version: '3'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: grammy-bot
    command: npm run start
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
